index.html
I have used the template from the **README.md**
The fact is:
*"Coding will soon be as important as reading."*
=> Added a fact tot the website

index.html
Added new AI fact to the webpage as a part of closing Issue #15.
=> Added a New Fact for Issue #15

index.html, script.js
Navbar: Sticky top class added
Search Bar: working Search Bar added
You may close #20
=> Update Navbar and Search bar

index.html, styles.css
Problems:
-footer was not sticking at the bottom
-responsive design of genre cards section was not working properly
Solution:
-footer fixed
-responsive design fixed
=> fixed the footer and responsive design of the website

index.html
Added a new interesting fact about science.
And also starred the repo.
=> Added fact 19

index.html
=> Added Fact 21 in index.html

index.html
=> Add Fact 22

index.html
=> created a random fact

index.html
Hello! @minhaj-313 Please check my pr.
=> Added fact 25

index.html
=> Added fact - 26

index.html
=> added fact -27

index.html
=> added a new fact

index.html
=> Added new fact

index.html
=> Added fact 35

index.html
=> added a fact

index.html, styles.css
I have improved ui  of homepage and top button as in below screenshot
issue no : #61
=> improved ui of homepage and buttons improved

script.js
=> Typing text animation js file added

index.html
i add this code under issue - [https://github.com/minhaj-313/Facts-Website/issues/8](url)
=> Adding Fact

index.html
Added 2 facts listed under fact no.40 and fact no.41.
=> Added a fact.

styles.css
Closes #69  
- Text and icons are now aligned at center
- Added padding and margin to image 
@minhaj-313 Can you please merge this PR with **hacktoberfest-accepted** tag
=> Fixed design of cards

script.js
I updated the typewriter() function to use arrow function syntax and const declarations instead of var. I also added a check to exit the function if the destination element is not found, and added an event listener to call the typewriter() function when the DOM is ready.
=> add some updates

index.html, styles.css
optimized view for mobile screen.
social buttons were not in center for mobile view.
unnecessary padding removed.
nothing changed in other style
review this @minhaj-313
=> responsive made for modile screen and css changed for social buttons

index.html
Added new fact under hacktoberfest
=> Update index.htm 

index.html
=> Update index.html under hacktoberfest

index.html, script.js, styles.css
Added Next and Previous Button to previous 10 fact at a time...
Also there is a Fact 44 added
DEMO : https://harshit1142.github.io/Facts-Website/
=> Add Pagination in Home Page
